models/aluno.py
""" from ..extensions import db


class Aluno(db.Model):
    __tablename__ = "alunos"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(150))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    ra = db.Column(db.Integer, unique=True)

    def __repr__(self):
        return "<Uc(nome={}, email={}, ra={})>".format(self.nome, self.email, self.ra)
 """

models/uc.py
from ..extensions import db


class Uc(db.Model):
    __tablename__ = "ucs"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(150))
    tipo = db.Column(db.String(50))
    inicio = db.Column(db.Date)
    fim = db.Column(db.Date)

    def __repr__(self):
        return "<Uc(nome={}, tipo={}, inicio={}, fim{})>".format(self.nome, self.tipo, self.inicio, self.fim)

models/user.py
from flask_login import UserMixin
from ..extensions import db


class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(150))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))


def __repr__(self):
    return "<Uc(nome={}, email={}>".format(self.nome, self.email)

__init__.py
from flask import Flask
from .extensions import db, migrate, login_manager
from .routes.ucBp import ucBp
from .routes.main import main
from .routes.authBp import authBp
from .models.user import User


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'Alguma-chave-SECRETA'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app)
    login_manager.login_view = 'authBp.login'
    login_manager.init_app(app)

    app.register_blueprint(main)
    app.register_blueprint(ucBp)
    app.register_blueprint(authBp)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

routes/aluno.py
""" from flask import Blueprint, render_template, request, redirect, url_for

from ..extensions import db
from ..models.aluno import Alunos
from datetime import date, datetime

alBp = Blueprint('alBp', __name__)


@alBp.route('/alunos')
def alBp_list():
    alBp_query = alBp.query.all()
    return render_template('alBp_list.html', alBp=alBp_query)


@alBp.route('/alunos/add', methods=['POST'])
def add_alBp():

    sNome = request.form["nome"]
    sTipo = request.form["tipo"]
    dInicio = datetime.strptime(request.form["inicio"], '%Y-%m-%d')
    dFim = datetime.strptime(request.form["fim"], '%Y-%m-%d')

    uc = Uc(nome=sNome, tipo=sTipo, inicio=dInicio, fim=dFim)
    db.session.add(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))


@alBp.route('/uc/update/<uc_id>')
def update_uc(uc_id=0):
    uc_query = Uc.query.filter_by(id=uc_id).first()
    return render_template('uc_update.html', uc=uc_query)


@alBp.route('/uc/upd', methods=['POST'])
def upd_uc():

    iUc = request.form["id"]
    sNome = request.form["nome"]
    sTipo = request.form["tipo"]
    dInicio = datetime.strptime(request.form["inicio"], '%Y-%m-%d')
    dFim = datetime.strptime(request.form["fim"], '%Y-%m-%d')

    uc = Uc.query.filter_by(id=iUc).first()
    uc.nome = sNome
    uc.tipo = sTipo
    uc.inicio = dInicio
    uc.fim = dFim
    db.session.add(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))


@alBp.route('/uc/delete/<uc_id>')
def delete_uc(uc_id=0):
    uc_query = Uc.query.filter_by(id=uc_id).first()
    return render_template('uc_delete.html', uc=uc_query)


@alBp.route('/uc/dlt', methods=['POST'])
def dtl_uc():

    iUc = request.form["id"]
    uc = Uc.query.filter_by(id=iUc).first()
    db.session.delete(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))
 """

routes/authBp.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required

from ..extensions import db
from ..models.user import User

authBp = Blueprint('authBp', __name__)


@authBp.route('/login')
def login():
    return render_template('login.html')


@authBp.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Dados de login inválidos')
        return redirect(url_for('authBp.login'))

    login_user(user, remember=remember)
    return redirect(url_for('ucBp.uc_list'))


@authBp.route('/signup')
def signup():
    return render_template('signup.html')


@authBp.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    nome = request.form.get('nome')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Endereço de e-mail indisponível')
        return redirect(url_for('authBp.signup'))

    new_user = User(email=email, nome=nome,
                    password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('authBp.login'))


@authBp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

routes/main.py
from flask import Blueprint, render_template
from ..extensions import db

main = Blueprint('main', __name__)


@main.route('/')
def index():
    db.create_all()
    return render_template('index.html')

routes/ucBp.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from ..extensions import db
from ..models.uc import Uc
from datetime import date, datetime

ucBp = Blueprint('ucBp', __name__)


@ucBp.route('/uc')
def uc_list():
    db.create_all()
    ucs_query = Uc.query.all()
    return render_template('uc_list.html', ucs=ucs_query)


@ucBp.route('/uc/create')
@login_required
def create_uc():
    return render_template('uc_create.html')


@ucBp.route('/uc/add', methods=['POST'])
@login_required
def add_uc():

    sNome = request.form["nome"]
    sTipo = request.form["tipo"]
    dInicio = datetime.strptime(request.form["inicio"], '%Y-%m-%d')
    dFim = datetime.strptime(request.form["fim"], '%Y-%m-%d')

    uc = Uc(nome=sNome, tipo=sTipo, inicio=dInicio, fim=dFim)
    db.session.add(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))


@ucBp.route('/uc/update/<uc_id>')
@login_required
def update_uc(uc_id=0):
    uc_query = Uc.query.filter_by(id=uc_id).first()
    return render_template('uc_update.html', uc=uc_query)


@ucBp.route('/uc/upd', methods=['POST'])
@login_required
def upd_uc():

    iUc = request.form["id"]
    sNome = request.form["nome"]
    sTipo = request.form["tipo"]
    dInicio = datetime.strptime(request.form["inicio"], '%Y-%m-%d')
    dFim = datetime.strptime(request.form["fim"], '%Y-%m-%d')

    uc = Uc.query.filter_by(id=iUc).first()
    uc.nome = sNome
    uc.tipo = sTipo
    uc.inicio = dInicio
    uc.fim = dFim
    db.session.add(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))


@ucBp.route('/uc/delete/<uc_id>')
@login_required
def delete_uc(uc_id=0):
    uc_query = Uc.query.filter_by(id=uc_id).first()
    return render_template('uc_delete.html', uc=uc_query)


@ucBp.route('/uc/dlt', methods=['POST'])
@login_required
def dtl_uc():

    iUc = request.form["id"]
    uc = Uc.query.filter_by(id=iUc).first()
    db.session.delete(uc)
    db.session.commit()

    return redirect(url_for('ucBp.uc_list'))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>UC Controler</title>
</head>

<body>
    <section class="hero is-primary is-fullheight" style="text-align: center;">

        <div class="hero-head">
            <nav class="navbar navbar-expand-lg bg-light">
                <div class="container-fluid">
                    <div id="navbarNavAltMarkup" class="navbar-collapse">
                        <div class="navbar-nav">
                            <a href="{{ url_for('main.index') }}" class="nav-item nav-link active">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('ucBp.uc_list') }}" class="nav-item nav-link active">
                                UC List
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('authBp.login') }}" class="nav-item nav-link active">
                                Login
                            </a>
                            <a href="{{ url_for('authBp.signup') }}" class="nav-item nav-link active">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('authBp.logout') }}" class="navbar-item nav-link active">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
    UC Controler
</h1>
<h2 class="subtitle">
    Organizador de Unidades Curriculares e Cursos de Extensão
</h2>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="mb-3">
                <div class="form-label">
                    <input class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" type="email"
                        name="email" placeholder="Email">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="form-control" id="exampleInputPassword1" type="password" name="password"
                        placeholder="Senha">
                </div>
            </div>
            <div class="mb-3 form-check">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0]}}. Go to <a href="{{ url_for('authBp.login')}}">Login</a>"
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="mb-3">
                <div id="emailHelp" class="form-text">
                    <input class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" type="email"
                        name="email" placeholder="Email">
                </div>
            </div>

            <div class="mb-3">
                <div class="control">
                    <input class="form-control" type="text" name="nome" placeholder="Nome" autofocus="">
                </div>
            </div>

            <div class="mb-3">
                <div for="exampleInputPassword1" class="form-label">
                    <input class="form-control" id="exampleInputPassword1" type="password" name="password"
                        placeholder="Senha">
                </div>
            </div>

            <button class="btn btn-primary">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

templates/uc_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>UC</title>
</head>

<body>
    <h1 style="text-align: center;">CRUD UC</h1>
    <form action="/uc/add" method="POST">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <tbody>
                        <tr>
                            <td>Nome: </td>
                            <td><input type="text" name="nome" id="nome" required></td>
                        </tr>
                        <tr>
                            <td>Tipo: </td>
                            <td><input type="radio" name="tipo" id="tipo" value="Curso de Extensão" required>Curso de
                                Extensão
                                <input type="radio" name="tipo" id="tipo" value="Unidade Curricular" required>Unidaded
                                Curricular
                            </td>
                        </tr>
                        <tr>
                            <td>Data Início: </td>
                            <td><input type="date" name="inicio" id="inicio" required format="dd/mm/yyyy"
                                    placeholder="DD-MM-YYYY"></td>
                        </tr>
                        <tr>
                            <td>Data Fim: </td>
                            <td><input type="date" name="fim" id="fim" required format="dd/mm/yyyy"
                                    placeholder="DD-MM-YYYY"></td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" value="Inserir"></td>
                        </tr>
                    </tbody>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

templates/uc_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>UC</title>
</head>

<body>
    <h1 style="text-align: center;">Quer mesmo apagar este componente curricular?</h1>
    <form action="/uc/dlt" method="POST">
        <input type="hidden" id="id" name="id" value="{{uc.id}}">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Nome: </td>
                                <td>{{uc.nome}}</td>
                            </tr>
                            <tr>
                                <td>Tipo: </td>
                                <td>{{uc.tipo}}</td>
                            </tr>
                            <tr>
                                <td>Data Inicio: </td>
                                <td>{{uc.inicio}}</td>
                            </tr>
                            <tr>
                                <td>Data Fim: </td>
                                <td>{{uc.fim}}</td>
                            </tr>
                            <tr>
                                <td colspan="2"><input type="submit" value="Apagar"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

templates/uc_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>UC</title>
</head>

<body>
    <h1 style="text-align: center;">CRUD UC</h1>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <table class="table">
                    <thead>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Início</th>
                        <th>Fim</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {% for uc in ucs%}
                        <tr>
                            <td>{{uc.nome}}</td>
                            <td>{{uc.tipo}}</td>
                            <td>{{uc.inicio}}</td>
                            <td>{{uc.fim}}</td>
                            <td><a href="/uc/update/{{uc.id}}" class="btn btn-primary btn-lg active" role="button"
                                    aria-pressed="true">Alterar</a>
                                <a href="/uc/delete/{{uc.id}}" class="btn btn-danger btn-lg active" role="button"
                                    aria-pressed="true">Apagar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="/uc/create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Novo</a>

            </div>
        </div>
    </div>
</body>

</html>

templates/uc_update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>UC</title>
</head>

<body>
    <h1 style="text-align: center;">CRUD UC</h1>
    <form action="/uc/upd" method="POST">
        <input type="hidden" id="id" name="id" value="{{uc.id}}">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Nome: </td>
                                <td><input type="text" name="nome" id="nome" value="{{uc.nome}}" required></td>
                            </tr>
                            <tr>
                                <td>Tipo: </td>
                                <td><input type="radio" name="tipo" id="tipo" value="Curso de Extensão" required
                                        {{"checked" if uc.tipo=="Curso de Extensão" else "" }}> Curso de Extensão
                                    <input type="radio" name="tipo" id="tipo" value="Unidade Curricular" required
                                        {{"checked" if uc.tipo=="Unidade Curricular" else "" }}> Unidade Curricular
                                </td>
                            </tr>
                            <tr>
                                <td>Data Início: </td>
                                <td><input type="date" name="inicio" id="inicio" required format="dd/mm/yyyy"
                                        placeholder="DD-MM-YYYY" value="{{uc.inicio}}"></td>
                            </tr>
                            <tr>
                                <td>Data Fim: </td>
                                <td><input type="date" name="fim" id="fim" required format="dd/mm/yyyy"
                                        placeholder="DD-MM-YYYY" value="{{uc.fim}}"></td>
                            </tr>
                            <tr>
                                <td colspan="2"><input type="submit" value="Alterar"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
</body>

</html>